export let root = document.getElementById('rootVisualizacion')



 import {carts} from './carts_has_products.js';
 export let opcionChp = document.getElementById('opcionCarts_has_products')
 export function opcionCarts_has_products(){


     root.innerHTML = 
       '<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[0][0]+'</div>'    +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[0][1]+'</div>'     +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[0][2]+'</div>'     +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[0][3]+'</div>'     +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[1][0]+'</div>'    +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[1][1]+'</div>'     +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[1][2]+'</div>'     +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[1][3]+'</div>'     +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[2][0]+'</div>'    +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[2][1]+'</div>'     +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[2][2]+'</div>'     +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[2][3]+'</div>'     +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[3][0]+'</div>'    +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[3][1]+'</div>'     +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[3][2]+'</div>'     +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[3][3]+'</div>'     +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[4][0]+'</div>'    +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[4][1]+'</div>'     +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[4][2]+'</div>'     +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[4][3]+'</div>'     +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[5][0]+'</div>'    +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[5][1]+'</div>'     +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[5][2]+'</div>'     +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[5][3]+'</div>'     +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[6][0]+'</div>'    +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[6][1]+'</div>'     +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[6][2]+'</div>'     +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[6][3]+'</div>'     +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[7][0]+'</div>'    +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[7][1]+'</div>'     +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[7][2]+'</div>'     +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[7][3]+'</div>'     +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[8][0]+'</div>'    +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[8][1]+'</div>'     +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[8][2]+'</div>'     +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[8][3]+'</div>'     +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[9][0]+'</div>'    +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[9][1]+'</div>'     +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[9][2]+'</div>'     +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[9][3]+'</div>'     +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[10][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[10][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[10][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[10][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[11][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[11][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[11][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[11][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[12][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[12][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[12][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[12][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[13][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[13][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[13][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[13][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[14][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[14][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[14][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[14][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[15][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[15][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[15][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[15][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[16][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[16][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[16][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[16][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[17][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[17][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[17][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[17][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[18][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[18][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[18][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[18][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[19][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[19][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[19][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[19][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[20][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[20][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[20][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[20][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[21][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[21][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[21][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[21][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[22][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[22][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[22][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[22][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[23][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[23][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[23][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[23][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[24][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[24][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[24][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[24][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[25][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[25][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[25][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[25][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[26][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[26][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[26][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[26][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[27][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[27][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[27][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[27][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[28][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[28][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[28][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[28][3]+'</div>'    +'</section>'
      +'<section class="opcionCarts_has_products">'+   '<div>'+'<div>'+'Identificación del carrito de compras'+'</div>'+carts[29][0]+'</div>'   +   '<div>'+'<div>'+'ID del producto'+'</div>'+carts[29][1]+'</div>'    +   '<div>'+'<div>'+'ID de la opción'+'</div>'+carts[29][2]+'</div>'    +   '<div>'+'<div>'+'cantidad'+'</div>'+carts[29][3]+'</div>'    +'</section>'
    
      
 }
 opcionChp.addEventListener('click', opcionCarts_has_products)



import {category} from './category.js';//Importacion de la Matriz
export let opcionC = document.getElementById('opcionCategory');//Se tre la opcion del HTML


//Funcion para el Evento
export function opcionCategory(){
    root.innerHTML = 
      '<section class="opcionCategory">'+'<div>'+'<div>'+'ID de la categoria'+'</div>' +'<div>'+category[0][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Nombre de la categoria'+'</div>' +'<div>'+category[0][1]+'</div>'+'</div>'+     '</section>'
     +'<section class="opcionCategory">'+'<div>'+'<div>'+'ID de la categoria'+'</div>' +'<div>'+category[1][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Nombre de la categoria'+'</div>' +'<div>'+category[1][1]+'</div>'+'</div>'+     '</section>'
     +'<section class="opcionCategory">'+'<div>'+'<div>'+'ID de la categoria'+'</div>' +'<div>'+category[2][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Nombre de la categoria'+'</div>' +'<div>'+category[2][1]+'</div>'+'</div>'+     '</section>'
     +'<section class="opcionCategory">'+'<div>'+'<div>'+'ID de la categoria'+'</div>' +'<div>'+category[3][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Nombre de la categoria'+'</div>' +'<div>'+category[3][1]+'</div>'+'</div>'+     '</section>'
     +'<section class="opcionCategory">'+'<div>'+'<div>'+'ID de la categoria'+'</div>' +'<div>'+category[4][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Nombre de la categoria'+'</div>' +'<div>'+category[4][1]+'</div>'+'</div>'+     '</section>'
     +'<section class="opcionCategory">'+'<div>'+'<div>'+'ID de la categoria'+'</div>' +'<div>'+category[5][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Nombre de la categoria'+'</div>' +'<div>'+category[5][1]+'</div>'+'</div>'+     '</section>'
     +'<section class="opcionCategory">'+'<div>'+'<div>'+'ID de la categoria'+'</div>' +'<div>'+category[6][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Nombre de la categoria'+'</div>' +'<div>'+category[6][1]+'</div>'+'</div>'+     '</section>'
    
    

}
opcionC.addEventListener('click', opcionCategory)//Evento click ejecutada por la opcion

/** *************************************************************************/
import {option} from './option.js';//Importacion de la Matriz
export let opcionO = document.getElementById('opcionOption');//Se tre la opcion del HTML


//Funcion para el Evento
export function opcionOption(){
    root.innerHTML = 
       '<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[0][0]+'</div>'+'</div>'       +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[0][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[1][0]+'</div>'+'</div>'       +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[1][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[2][0]+'</div>'+'</div>'       +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[2][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[3][0]+'</div>'+'</div>'       +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[3][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[4][0]+'</div>'+'</div>'       +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[4][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[5][0]+'</div>'+'</div>'       +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[5][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[6][0]+'</div>'+'</div>'       +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[6][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[7][0]+'</div>'+'</div>'       +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[7][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[8][0]+'</div>'+'</div>'       +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[8][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[9][0]+'</div>'+'</div>'       +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[9][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[10][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[10][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[11][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[11][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[12][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[12][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[13][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[13][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[14][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[14][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[15][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[15][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[16][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[16][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[17][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[17][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[18][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[18][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[19][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[19][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[20][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[20][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[21][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[21][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[22][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[22][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[23][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[23][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[24][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[24][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[25][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[25][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[26][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[26][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[27][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[27][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[28][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[28][1]+'</div>'+'</div>'    +    '</section>'
      +'<section class="opcionOption">'  +     '<div>'+'<div>'+'ID de la opción'+'</div>' +'<div>'+option[29][0]+'</div>'+'</div>'      +   '<div>'+'<div>'+'Nombre de la opcion'+'</div>' +'<div>'+option[29][1]+'</div>'+'</div>'    +    '</section>'
    
    

}
opcionO.addEventListener('click', opcionOption)//Evento click ejecutada por la opcion

/*************************************************************************************************************** */
import {orden} from './order.js';//Importacion de la Matriz
export let opcionOr = document.getElementById('opcionOrder');//Se tre la opcion del HTML


//Funcion para el Evento
export function opcionOrder(){
    root.innerHTML = 
      '<section class="opcionOrder">'+'<div>'+'<div>'+'ID de orden'+'</div>' +'<div>'+orden[0][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Total de objetos'+'</div>' +'<div>'+orden[0][1]+'</div>'+'</div>'     +        '<div>'+'<div>'+'Gastos de envío'+'</div>' +'<div>'+orden[0][2]+'</div>'+'</div>'+    '<div>'+'<div>'+'Impuesto'+'</div>' +'<div>'+orden[0][3]+'</div>'+'</div>'+     '<div>'+'<div>'+'Total del costo'+'</div>' +'<div>'+orden[0][4]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de orden'+'</div>' +'<div>'+orden[0][5]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de entrega'+'</div>' +'<div>'+orden[0][6]+'</div>'+'</div>'+     '<div>'+'<div>'+'Nombre del barco'+'</div>' +'<div>'+orden[0][7]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del barco'+'</div>' +'<div>'+orden[0][8]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del envio'+'</div>' +'<div>'+orden[0][9]+'</div>'+'</div>'+     '<div>'+'<div>'+'Numero de rastreo'+'</div>' +'<div>'+orden[0][10]+'</div>'+'</div>'+    '<div>'+'<div>'+'Estado de entrega'+'</div>' +'<div>'+orden[0][11]+'</div>'+'</div>'+   '</section>'
     +'<section class="opcionOrder">'+'<div>'+'<div>'+'ID de orden'+'</div>' +'<div>'+orden[1][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Total de objetos'+'</div>' +'<div>'+orden[1][1]+'</div>'+'</div>'     +        '<div>'+'<div>'+'Gastos de envío'+'</div>' +'<div>'+orden[1][2]+'</div>'+'</div>'+    '<div>'+'<div>'+'Impuesto'+'</div>' +'<div>'+orden[1][3]+'</div>'+'</div>'+     '<div>'+'<div>'+'Total del costo'+'</div>' +'<div>'+orden[1][4]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de orden'+'</div>' +'<div>'+orden[1][5]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de entrega'+'</div>' +'<div>'+orden[1][6]+'</div>'+'</div>'+     '<div>'+'<div>'+'Nombre del barco'+'</div>' +'<div>'+orden[1][7]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del barco'+'</div>' +'<div>'+orden[1][8]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del envio'+'</div>' +'<div>'+orden[1][9]+'</div>'+'</div>'+     '<div>'+'<div>'+'Numero de rastreo'+'</div>' +'<div>'+orden[1][10]+'</div>'+'</div>'+    '<div>'+'<div>'+'Estado de entrega'+'</div>' +'<div>'+orden[1][11]+'</div>'+'</div>'+   '</section>'
     +'<section class="opcionOrder">'+'<div>'+'<div>'+'ID de orden'+'</div>' +'<div>'+orden[2][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Total de objetos'+'</div>' +'<div>'+orden[2][1]+'</div>'+'</div>'     +        '<div>'+'<div>'+'Gastos de envío'+'</div>' +'<div>'+orden[2][2]+'</div>'+'</div>'+    '<div>'+'<div>'+'Impuesto'+'</div>' +'<div>'+orden[2][3]+'</div>'+'</div>'+     '<div>'+'<div>'+'Total del costo'+'</div>' +'<div>'+orden[2][4]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de orden'+'</div>' +'<div>'+orden[2][5]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de entrega'+'</div>' +'<div>'+orden[2][6]+'</div>'+'</div>'+     '<div>'+'<div>'+'Nombre del barco'+'</div>' +'<div>'+orden[2][7]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del barco'+'</div>' +'<div>'+orden[2][8]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del envio'+'</div>' +'<div>'+orden[2][9]+'</div>'+'</div>'+     '<div>'+'<div>'+'Numero de rastreo'+'</div>' +'<div>'+orden[2][10]+'</div>'+'</div>'+    '<div>'+'<div>'+'Estado de entrega'+'</div>' +'<div>'+orden[2][11]+'</div>'+'</div>'+   '</section>'
     +'<section class="opcionOrder">'+'<div>'+'<div>'+'ID de orden'+'</div>' +'<div>'+orden[3][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Total de objetos'+'</div>' +'<div>'+orden[3][1]+'</div>'+'</div>'     +        '<div>'+'<div>'+'Gastos de envío'+'</div>' +'<div>'+orden[3][2]+'</div>'+'</div>'+    '<div>'+'<div>'+'Impuesto'+'</div>' +'<div>'+orden[3][3]+'</div>'+'</div>'+     '<div>'+'<div>'+'Total del costo'+'</div>' +'<div>'+orden[3][4]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de orden'+'</div>' +'<div>'+orden[3][5]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de entrega'+'</div>' +'<div>'+orden[3][6]+'</div>'+'</div>'+     '<div>'+'<div>'+'Nombre del barco'+'</div>' +'<div>'+orden[3][7]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del barco'+'</div>' +'<div>'+orden[3][8]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del envio'+'</div>' +'<div>'+orden[3][9]+'</div>'+'</div>'+     '<div>'+'<div>'+'Numero de rastreo'+'</div>' +'<div>'+orden[3][10]+'</div>'+'</div>'+    '<div>'+'<div>'+'Estado de entrega'+'</div>' +'<div>'+orden[3][11]+'</div>'+'</div>'+   '</section>'
     +'<section class="opcionOrder">'+'<div>'+'<div>'+'ID de orden'+'</div>' +'<div>'+orden[4][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Total de objetos'+'</div>' +'<div>'+orden[4][1]+'</div>'+'</div>'     +        '<div>'+'<div>'+'Gastos de envío'+'</div>' +'<div>'+orden[4][2]+'</div>'+'</div>'+    '<div>'+'<div>'+'Impuesto'+'</div>' +'<div>'+orden[4][3]+'</div>'+'</div>'+     '<div>'+'<div>'+'Total del costo'+'</div>' +'<div>'+orden[4][4]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de orden'+'</div>' +'<div>'+orden[4][5]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de entrega'+'</div>' +'<div>'+orden[4][6]+'</div>'+'</div>'+     '<div>'+'<div>'+'Nombre del barco'+'</div>' +'<div>'+orden[4][7]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del barco'+'</div>' +'<div>'+orden[4][8]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del envio'+'</div>' +'<div>'+orden[4][9]+'</div>'+'</div>'+     '<div>'+'<div>'+'Numero de rastreo'+'</div>' +'<div>'+orden[4][10]+'</div>'+'</div>'+    '<div>'+'<div>'+'Estado de entrega'+'</div>' +'<div>'+orden[4][11]+'</div>'+'</div>'+   '</section>'
     +'<section class="opcionOrder">'+'<div>'+'<div>'+'ID de orden'+'</div>' +'<div>'+orden[5][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Total de objetos'+'</div>' +'<div>'+orden[5][1]+'</div>'+'</div>'     +        '<div>'+'<div>'+'Gastos de envío'+'</div>' +'<div>'+orden[5][2]+'</div>'+'</div>'+    '<div>'+'<div>'+'Impuesto'+'</div>' +'<div>'+orden[5][3]+'</div>'+'</div>'+     '<div>'+'<div>'+'Total del costo'+'</div>' +'<div>'+orden[5][4]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de orden'+'</div>' +'<div>'+orden[5][5]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de entrega'+'</div>' +'<div>'+orden[5][6]+'</div>'+'</div>'+     '<div>'+'<div>'+'Nombre del barco'+'</div>' +'<div>'+orden[5][7]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del barco'+'</div>' +'<div>'+orden[5][8]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del envio'+'</div>' +'<div>'+orden[5][9]+'</div>'+'</div>'+     '<div>'+'<div>'+'Numero de rastreo'+'</div>' +'<div>'+orden[5][10]+'</div>'+'</div>'+    '<div>'+'<div>'+'Estado de entrega'+'</div>' +'<div>'+orden[5][11]+'</div>'+'</div>'+   '</section>'
     +'<section class="opcionOrder">'+'<div>'+'<div>'+'ID de orden'+'</div>' +'<div>'+orden[6][0]+'</div>'+'</div>'      +       '<div>'+'<div>'+'Total de objetos'+'</div>' +'<div>'+orden[6][1]+'</div>'+'</div>'     +        '<div>'+'<div>'+'Gastos de envío'+'</div>' +'<div>'+orden[6][2]+'</div>'+'</div>'+    '<div>'+'<div>'+'Impuesto'+'</div>' +'<div>'+orden[6][3]+'</div>'+'</div>'+     '<div>'+'<div>'+'Total del costo'+'</div>' +'<div>'+orden[6][4]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de orden'+'</div>' +'<div>'+orden[6][5]+'</div>'+'</div>'+     '<div>'+'<div>'+'Fecha de entrega'+'</div>' +'<div>'+orden[6][6]+'</div>'+'</div>'+     '<div>'+'<div>'+'Nombre del barco'+'</div>' +'<div>'+orden[6][7]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del barco'+'</div>' +'<div>'+orden[6][8]+'</div>'+'</div>'+     '<div>'+'<div>'+'Direccion del envio'+'</div>' +'<div>'+orden[6][9]+'</div>'+'</div>'+     '<div>'+'<div>'+'Numero de rastreo'+'</div>' +'<div>'+orden[6][10]+'</div>'+'</div>'+    '<div>'+'<div>'+'Estado de entrega'+'</div>' +'<div>'+orden[6][11]+'</div>'+'</div>'+   '</section>'
    
    

}
opcionOr.addEventListener('click', opcionOrder)//Evento click ejecutada por la opcion



import {shoppingcart} from './shoppingcart.js';
export let opcionS = document.getElementById('opcionShopping');
export function opcionShopping(){
    root.innerHTML = 
        '<div class="opcionShopping">'  +   '<div>'+shoppingcart[0][0]+'</div>'    +   '<div>'+shoppingcart[0][1]+'</div>'  +   '</div>'
    +   '<div class="opcionShopping">'  +   '<div>'+shoppingcart[1][0]+'</div>'    +   '<div>'+shoppingcart[1][1]+'</div>'  +   '</div>'
    +   '<div class="opcionShopping">'  +   '<div>'+shoppingcart[2][0]+'</div>'    +   '<div>'+shoppingcart[2][1]+'</div>'  +   '</div>'
}
opcionS.addEventListener('click', opcionShopping)